name: Deploy Backend to Function App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r azure_upload_function/requirements.txt --target azure_upload_function/.python_packages/lib/site-packages

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Function App
        uses: Azure/functions-action@v1
        with:
          app-name: dataorch-new-funcapp
          package: azure_upload_function
          scm-do-build-during-deployment: false
          enable-oryx-build: false
